django1/src/blog/urls.py
from .views import *
from django.urls import path

app_name = 'blog'
urlpatterns = [
    path('', Index.as_view(), name= 'index'),
    path('<int:pk>/', Detail.as_view(), name= 'detail'),
    path('posting/', Posting.as_view(), name= 'postiong')
]

django1/src/customlogin/urls.py
#하위 URLConf
#app_name: 하위 URLConf 파일의 등록된 URL들의 그룹명
#urlpatterns: URL과 뷰함수를 이그트형태로 등록하는 변수
from django.urls import path
from .views import *

app_name = 'cl'
urlpatterns = [
    path('signup/', signup, name= 'signup'),
    path('signin/', signin, name= 'signin'),
    path('signout/', signout, name= 'signout'),
]

django1/src/django1/urls.py
from django.contrib import admin
from django.urls import path, include
from bookmark.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('booklist/', booklist),
    path('<int:bookid>/', getbook),
    path('vote/', include('vote.urls')),
    path('cl/', include('customlogin.urls')),
    path('blog/', include('blog.urls')),
    
    #social_django 어플리케이션의 하위 urlconf 등록
    path('auth/', include('social_django.urls', namespace= 'social'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django1/src/vote/urls.py
#하위 URLConf
#app_name: 하위 URLConf 파일의 등록된 URL들의 그룹명
#urlpatterns: URL과 뷰함수를 이그트형태로 등록하는 변수
from django.urls import path
from .views import *

app_name = 'vote'
urlpatterns = [
    path('', index, name= 'index'),
    path('<int:q_id>/', detail, name= 'detail'),
    path('vote/', vote, name= 'vote'),
    path('result/<int:q_id>/', result, name= 'result'),
    path('qr', qregister, name= 'qr'),
    path('qu/<int:q_id>/', qupdate, name= 'qu'),
    path('qd/<int:q_id>/', qdelete, name= 'qd'),
    path('cr/', cregister, name= 'cr'),
    path('cu/<int:c_id>/', cupdate, name= 'cu'),
    path('cd/<int:c_id>/', cdelete, name= 'cd'),
]

django1/src/blog/models.py
from django.db import models
from django.contrib.auth.models import User
#카테고리
    #카테고리 이름
class PostType(models.Model):
    name = models.CharField('카테고리', max_length=20)
    def __str__(self):
        return self.name
    
#글 정보
    #제목, 글쓴이-외래키, 글내용, 작성일, 카테고리-외래키
class Post(models.Model):
    category = models.ForeignKey(PostType, on_delete=models.CASCADE)
    headline = models.CharField('제목', max_length=200)
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    content = models.TextField('내용', null=True, blank=True)
    pub_date =models.DateTimeField('작성일', auto_now_add=True)
    class Meta:
        ordering = ['-pub_date']
#글에 포함된 이미지 정보
    #글-외래키, 이미지파일(ImageFiled, Pillow(파이썬에서 사용되는 대표적인 이미지 처리모듈)모듈 필요)
class PostImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField('이미지파일', upload_to='images/%Y/%m/%d')
    
#글에 포함된 첨부파일 정보
    #글-외래키, 파일
class PostFile(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    file = models.FileField('첨부파일', upload_to='files/%Y/%m/%d')
    

django1/src/blog/forms.py
from .models import Post
from django import forms

class PostForm(forms.ModelForm):
    file = forms.FileField(required=False, widget=forms.ClearableFileInput(attrs={'multiple':True}))
    image = forms.ImageField(required=False, widget=forms.ClearableFileInput(attrs={'multiple':True}))
    class Meta:
        model = Post
        fields = ['category', 'headline', 'content']

django1/src/blog/views.py
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from blog.models import Post, PostFile, PostImage
from blog.forms import PostForm
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse
from django.contrib.auth.mixins import LoginRequiredMixin

#제네릭뷰: 장고에서 제공하는 여러가지 뷰 기능을 구현한 클래스
#ListView: 특정 모델의 객체 목록을 다루는 기능이 구현
#DetailView: 특정 모델클래스의 객체 1개를 다루는 기능이 구현
#FormView: 특정 폼클래스를 다루는 기능이 구현

#index: 글목록이 뜨는 메인 페이지
class Index(ListView):
    template_name = 'blog/index.html'
    model = Post
    context_object_name = 'list'
    pageinate_by = 5

#detail: 글 상세보기 페이지
class Detail(DetailView):
    template_name = 'blog/detail.html'
    model = Post
    context_object_name = 'obj'

#posting: 글쓰기 페이지
class Posting(LoginRequiredMixin, FormView):
    template_name = 'blog/posting.html'
    form_class = PostForm
    context_object_name = 'f'
    
    def form_valid(self, form):
        p = form.save(commit=False)
        p.author = self.request.user
        p.save()
        for f in self.request.FILES.getlist('files'):
            pf = PostFile()
            pf.file = f
            pf.post = p
            pf.save()
        for i in self.request.FILES.getlist('images'):
            pi = PostImage()
            pi.post = p
            pi.image = i
            pi.save()
        return HttpResponseRedirect(reverse('blog:detail', args=(p.id,)))

django1/src/blog/templates/blog/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
<h3> 나만의 홈페이지 </h3>
<a href="/">북마크</a>
<a href="{% url 'vote:index' %}">설문조사</a>
<a href="{% url 'blog:index' %}">블로그</a>
<br>
{% if user.is_authenticated %}
	<p>{{user.last_name}} {{user.first_name}} 님 환영합니다.<a href="{% url 'cl:signout' %}">로그아웃</a></p>
{% else %}
	<a href="{% url 'cl:signin' %}">로그인</a>
	<a href="{% url 'cl:signup' %}">회원가입</a>
{% endif %}
<hr>
{% block content %}
	
{% endblock %}
</body>
</html>

django1/src/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block content %}
	<h3>[ {{obj.category}} ]{{obj.headline}}</h3>
	<p>{{obj.author}} / {{obj.pub_date}}</p>
	{% for f in obj.postfile_set.all %}
		<a href="{{f.file.url}}" download>첨부파일</a>
		<br>
	{% endfor %}
	{% for i in obj.postimage_set.all %}
		<img src="{{i.image.url}}" width="30%">
		<br>
	{% endfor %}
	<pre>{{obj.content}}</pre>
{% endblock %}

django1/src/blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}
	{% if page_obj.has_previous %}
		<a href="?page={{page_obj.previous_page_number}}">이전 페이지</a>
	{% endif %}
	
	{% if page_obj.has_next %}
		<a href="?page={{page_obj.next_page_number}}">다음페이지</a>
	{% endif %}
	<table width="90%">
		<tr>
			<th>글번호</th>
			<th>카테고리</th>
			<th>제목</th>
			<th>작성자</th>
			<th>작성일</th>
		</tr>
		{% for post in list %}
			<tr>
				<th>{{post.id}}</th>
				<th>{{post.category}}</th>
				<th>{{post.headline}}</th>
				<th>{{post.author}}</th>
				<th>{{post.pub_date}}</th>
			</tr>
		{% endfor %}
	</table>
{% endblock %}

django1/src/blog/templates/blog/posting.html
{% extends 'blog/base.html' %}

{% block content %}
	<h3>글 쓰기</h3>
	<form action="" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<table>
			{{form.as_table}}
		</table>
		<input type="submit" value="갱신">
	</form>
	<a href="{% url 'blog:index' %}">메인페이지로 돌아가기</a>
{% endblock %}