django1/src/blog/urls.py
from .views import *
from django.urls import path

app_name = 'blog'
urlpatterns = [
    path('', Index.as_view(), name= 'index'),
    path('<int:pk>/', Detail.as_view(), name= 'detail'),
    path('posting/', Posting.as_view(), name= 'postiong')
]

django1/src/django1/urls.py
from django.contrib import admin
from django.urls import path, include
from bookmark.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('booklist/', booklist),
    path('<int:bookid>/', getbook),
    path('vote/', include('vote.urls')),
    path('cl/', include('customlogin.urls')),
    path('blog/', include('blog.urls')),
    
    #social_django 어플리케이션의 하위 urlconf 등록
    path('auth/', include('social_django.urls', namespace= 'social'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django1/src/vote/urls.py
#하위 URLConf
#app_name: 하위 URLConf 파일의 등록된 URL들의 그룹명
#urlpatterns: URL과 뷰함수를 이그트형태로 등록하는 변수
from django.urls import path
from .views import *

app_name = 'vote'
urlpatterns = [
    path('', index, name= 'index'),
    path('<int:q_id>/', detail, name= 'detail'),
    path('vote/', vote, name= 'vote'),
    path('result/<int:q_id>/', result, name= 'result'),
    path('qr', qregister, name= 'qr'),
    path('qu/<int:q_id>/', qupdate, name= 'qu'),
    path('qd/<int:q_id>/', qdelete, name= 'qd'),
    path('cr/', cregister, name= 'cr'),
    path('cu/<int:c_id>/', cupdate, name= 'cu'),
    path('cd/<int:c_id>/', cdelete, name= 'cd'),
]

django1/src/vote/models.py
from django.db import models

'''
질문
질문제목 생성일

답변
어떤질문에 연결되있는지 답변내용 투표수
'''
class Question(models.Model):
    name = models.CharField('질문', max_length=100)
    date = models.DateTimeField('생성일')
    def __str__(self):
        return self.name
    class Meta:
        ordering = ['-date']
class Choice(models.Model):
    q = models.ForeignKey(Question, on_delete=models.CASCADE)
    name = models.CharField('항목', max_length=50)
    votes = models.IntegerField('투표수', default=0)
    def __str__(self):
        return self.q.name+'/'+self.name

django1/src/vote/forms.py
#form: html의 <form>태그에 들어가는 <input>태그들을 관리하는 클래스/기능
#모델클래스에 저장된 변수들에 맞춰 자동설정도 할수있고, 커스텀입력공간(비밀번호 확인)도 생성할수있음

#class 클래스명(ModelForm 또는 Form)
#ModelForm: 모델클래스를 기반으로 입력양식을 자동 생성할때 상속받는 클래스
#Form: 커스텀 입력양식을 생성할때 상속받는 클래스
#ModelForm을 상속받았을 때도 커스텀 입력양식을 생성할 수 있음

#폼 클래스의 객체를 함수를 통해서 html문서의 코드로 변환할 수 있음(<p>,<table>,<li>)
#예시) 폼클래스객체.as_p() -> 해당 폼 객체에 저장된 입력공간들을 <input>태그로 변환하고, 개별적으로 <p>태그로 묶은 문자열을 반환
from django.forms.models import ModelForm
from .models import Question, Choice

class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ['name']
        
class ChoiceForm(ModelForm):
    class Meta:
        model = Choice
        fields = ['q', 'name']

    

django1/src/vote/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from django.urls.base import reverse
from django.http.response import HttpResponseRedirect
from .forms import *
from _datetime import datetime
from django.contrib.auth.decorators import login_required
import os
#질문 리스트(index)
#질문 선택시 답변 항목제공(detail)
#웹 클라이언트가 선택한 답변항목의 투표수를 늘리는 처리(vote)
#웹 클라이언트가 선택한 질문의 답변 투표결과(result)
def index(request):
    qlist = Question.objects.all()
    return render(request, 'vote/index.html', {'objs':qlist})
def detail(request, q_id):
    q = get_object_or_404(Question, id=q_id)
    c_list = q.choice_set.all()
    return render(request, 'vote/detail.html', {'q':q, 'clist':c_list})
def vote(request):
    if request.method == "POST":
        c_id = request.POST.get('a')
        c = get_object_or_404(Choice, id=c_id)
        c.votes +=1
        c.save()
        return HttpResponseRedirect( reverse('vote:result', args=(c.q.id,)))
def result(request, q_id):
    q = get_object_or_404(Question, id=q_id)
    return render(request, 'vote/result.html', {'q':q})

@login_required
def qregister(request):
    if request.method == "GET":
        f = QuestionForm()
        return render(request, 'vote/qregister.html', {'f':f})
    elif request.method == "POST":
        f = QuestionForm(request.POST)
        if f.is_valid():
            print('cleaned_data["name"]', f.cleaned_data['name'])
            q = f.save(commit=False)
            q.date = datetime.now()
            print('데이터베이스에 저장되기 전 Question객체의 id값', q.id)
            q.save()
            print('데이터베이스에 저장된 후 id값', q.id)
            return HttpResponseRedirect(reverse('vote:detail', args=(q.id,)))
def qupdate(request, q_id):
    q = get_object_or_404(Question, id=q_id)
    if request.method == "GET":
        f = QuestionForm(instance = q)
        return render(request, 'vote/qregister.html', {'f':f})
    elif request.method == "POST":
        f = QuestionForm(request.POST, instance = q)
        if f.is_valid():
            qu = f.save()
            print('사용자 요청으로 찾으니 객체', q)
            print('값이 수정된 객체', qu)
            return HttpResponseRedirect(reverse('vote:detail', args=(q.id,)))
def qdelete(request, q_id):
    q = get_object_or_404(Question, id=q_id)
    print('데이터 베이스에 삭제되기전 id변수', q.id)
    q.delete()
    print('데이터 베이스에 삭제된 후 id변수', q.id)
    return HttpResponseRedirect(reverse('vote:index'))
def cregister(request):
    if request.method == "GET":
        f = ChoiceForm()
        return render(request, 'vote/cform.html', {'i':f.as_table()})
    elif request.method == "POST":
        f = ChoiceForm(request.POST)
        if f.is_valid():
            c = f.save()
            return HttpResponseRedirect(reverse('vote:detail', args=(c.q.id,)))
        else:
            return render(request, 'vote/cform.html', {'i':f.as_table(), 'error':'잘못된 임력입니다'})
def cupdate(request, c_id):
    c = get_object_or_404(Choice, id=c_id)
    if request.method == "GET":
        f = ChoiceForm(instance = c)
        return render(request, 'vote/cform.html', {'i':f.as_table()})
    elif request.method == "POST":
        f = ChoiceForm(request.POST, instance = c)
        if f.is_valid():
            f.save()
            return HttpResponseRedirect(reverse('vote:detail', args=(c.q.id,)))
def cdelete(request, c_id):
    c = get_object_or_404(Choice, id=c_id)
    c.delete()
    return HttpResponseRedirect(reverse('vote:detail', args=(c.q.id,)))

django1/src/vote/templates/vote/cform.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>답변항목 생성/수정 페이지</h1>
	{% if error %}
		<p style="color:red;">{{error}}</p>
	{% endif %}
	<form action="" method="post">
		{% csrf_token %}
		<table>
			{{i}}
		</table>
		<input type="submit" value="갱신">
	</form>
	<a href="{% url 'vote:index' %}">메인페이지로 돌아가기</a>
</body>
</html>

django1/src/vote/templates/vote/detail.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>{{q.name}}</h1>
	<p>{{q.date}}</p>
	<form action="{% url 'vote:vote'%}" method="post">
	{% csrf_token %}
	{% for c in clist %}
		<input type="radio", name="a" value="{{c.id}}">
		<label>{{c.name}}</label>
		<a href="{% url 'vote:cu' c.id %}">수정</a>
		<a href="{% url 'vote:cd' c.id %}">삭제</a><br>
	{% endfor %}
	<input type="submit" value="투표하기">
	</form>
	<a href="{%url 'vote:index'%}">메인 페이지로 돌아가기</a>
</body>
</html>

django1/src/vote/templates/vote/index.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>투표 어플리케이션</h1>
	<p>투표할 질문을 선택하세요</p>
	<table width=100%>
		<tr>
			<td>질문번호</td>
			<td>제목</td>
			<td>생성일</td>
		</tr>
		{% for q in objs %}
		<tr>
			<td>{{q.id}}</td>
			<td><a href="{%url 'vote:detail' q.id%}">{{q.name}}</a></td>
			<td>{{q.date}}</td>
			<td><a href="{%url 'vote:qu' q.id%}">수정</a><a href="{%url 'vote:qd' q.id%}">삭제</a></td>
		</tr>
		{% endfor %}
	</table>
	<a href="{% url 'vote:qr' %}">질문추가하기</a>
	<a href="{% url 'vote:cr' %}">항목추가하기</a>
</body>
</html>

django1/src/vote/templates/vote/qregister.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>질문 등록/수정 페이지</h1>
	<form action="" method="post">
		{% csrf_token %}
		{{f.as_p}}
		<input type="submit" value="질문 갱신">
	</form>
	<a href="{% url 'vote:index' %}">메인페이지로 돌아가기</a>
</body>
</html>

django1/src/vote/templates/vote/result.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>{{q.name}} 투표결과</h1>
	<ul>
	{% for c in q.choice_set.all %}
		<li>{{c.name}} - {{c.votes}} 표</li>
	{% endfor %}
	</ul>
	<a href="{%url 'vote:index'%}">메인 페이지로 돌아가기</a>
</body>
</html>